### ISSUE TITLE
development install error

### ISSUE THREAD

**Issue by wispyoureyes** [jupyterhub/jupyterlab-hub#18]
I‘m trying to install jupyterlab-hub on jupyterlab v0.26.0 :

`jupyter labextension link .`

and the following is the error:

```
npm pack /Users/adminastor/jupyterworkspace/extensions/jupyterlab-hub
node node-version-check.js
Uninstalling jupyterlab-hub from /Users/adminastor/anaconda/share/jupyter/lab/extensions
Traceback (most recent call last):
  File "/Users/adminastor/anaconda/bin/jupyter-labextension", line 11, in <module>
    load_entry_point('jupyterlab', 'console_scripts', 'jupyter-labextension')()
  File "/Users/adminastor/anaconda/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/adminastor/anaconda/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/adminastor/jupyterworkspace/jupyterlab-0.26.0/jupyterlab/labextensions.py", line 167, in start
    super(LabExtensionApp, self).start()
  File "/Users/adminastor/anaconda/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/Users/adminastor/jupyterworkspace/jupyterlab-0.26.0/jupyterlab/labextensions.py", line 89, in start
    raise e
  File "/Users/adminastor/jupyterworkspace/jupyterlab-0.26.0/jupyterlab/labextensions.py", line 85, in start
    build(self.app_dir, logger=self.log)
  File "/Users/adminastor/jupyterworkspace/jupyterlab-0.26.0/jupyterlab/commands.py", line 488, in build
    _ensure_package(app_dir, name=name, version=version, logger=logger)
  File "/Users/adminastor/jupyterworkspace/jupyterlab-0.26.0/jupyterlab/commands.py", line 744, in _ensure_package
    data = _get_package_template(app_dir, logger)
  File "/Users/adminastor/jupyterworkspace/jupyterlab-0.26.0/jupyterlab/commands.py", line 801, in _get_package_template
    data['jupyterlab']['mimeExtensions'].remove(item)
ValueError: list.remove(x): x not in list
```

**Comment by wispyoureyes** [comment]
I found an uninstalled_core_extensions  in `settings/build_config.json` named dashboard-extension，it used to be installed on my jupyterlab, but later I reinstalled my jupyterlab. So I delete this line of build_config，and it works.

```
{
    "uninstalled_core_extensions": {
        "dashboard-extension": "/Users/adminastor/jupyterworkspace/jupyterlab/extensions/dashboard-extension"
    }
}
```
