### ISSUE TITLE
jupyter labhub

### ISSUE THREAD

**Issue by enriqueartal** [jupyterhub/jupyterlab-hub#32]
I am not sure if it is the right place, but where "jupyter labhub" should be in jupyterhub?

**Comment by blink1073** [comment]
Hi @enriqueartal, that command is provided by JupyterLab, and the application is defined [here](https://github.com/jupyterlab/jupyterlab/blob/2c4ce90662cf8c85085aaadd648d3f48a399969d/jupyterlab/labhubapp.py).

**Comment by enriqueartal** [comment]
Thanks, but my issue is where this command must be in jupyterhub. Sorry for my ignorance.

**Comment by blink1073** [comment]
No worries, this is from my `jupyterhub_config.py` file:

```python
## The command used for starting notebooks.
c.Spawner.cmd = ['jupyter-labhub']
```

**Comment by enriqueartal** [comment]
Thanks, I tried without success:
500 : Internal Server Error
Failed to reach your server. Please try again later. Contact admin if the issue persists.

You can try restarting your server from the home page.

**Comment by blink1073** [comment]
The only other setting I have set explicitly is `c.Spawner.ip = '127.0.0.1'`.  There are some troubleshooting tips for 500 errors [here](https://jupyterhub.readthedocs.io/en/0.7.2/troubleshooting.html#error-after-spawning-my-single-user-server).

**Comment by itcarroll** [comment]
Please add that more specific instruction to the README's installation section ... i was also lost.

    ## The command used for starting notebooks.
    c.Spawner.cmd = ['jupyter-labhub']

**Comment by blink1073** [comment]
Done in https://github.com/jupyterhub/jupyterlab-hub/commit/785fbc7a71a3793b2c1ca136c0d3030a3a8e8124, cheers!

**Comment by riazarbi** [comment]
Another possible reason for 500 server error is that you have done all your pip and npm installs using sudo rather than root, but then you are trying to run your jupyterhub as root. When this happens the root spawner is told to spawn a labhub but it doesn't know where the extensions are. Long story short, if you are running your jupyterhub as root, which you would be if it starts as a system service, then you need to run the following AS ROOT - 
```
pip install jupyterlab
jupyter serverextension enable --py jupyterlab --sys-prefix
```
Regardless of where your `jupyterhub_config.py` sits

**Comment by enriqueartal** [comment]
It works!

**Comment by aboyle** [comment]
I'm having a similar hang-up here when I keep getting the error below after adding the c.Spawner command and the jupyter serverextension enable. I also get this just running jupyter-labhub from the command line. No problem running jupyterhub by itself.

```
Traceback (most recent call last):
File "/usr/local/bin/jupyter-labhub", line 7, in <module>
from jupyterlab.labhubapp import main
File "/usr/local/lib/python2.7/dist-packages/jupyterlab/labhubapp.py", line 8, in <module>
raise ImportError('You must have jupyterhub installed for this to work.')
```
