### ISSUE TITLE
webpack error Command failed with signal "SIGKILL".

### ISSUE THREAD

**Issue by bikashdube** [jupyterhub/jupyterlab-hub#44]
I am trying to install this in a working JupyterHub using pyenv to get a local python 3.6.4 environment. The extension always fails at the webpack step. have also run with the --debug flag but it has no verbose output for the failing step.

```
> /bin/npm pack /home/labhub/jupyterlab-hub
jupyterlab-hub-extension-0.8.1.tgz
> /bin/npm pack /home/labhub/jupyterlab-hub
jupyterlab-hub-extension-0.8.1.tgz
> node /home/labhub/.pyenv/versions/3.6.4/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.3.2
warning ../../../../../../../package.json: No license field
info No lockfile found.
[1/4] Resolving packages...
â  @jupyterlab/application@^0.15.4
â  @phosphor/widgets@^1.5.0
â  @phosphor/dragdrop@^1.3.0
â  codemirror@~5.24.2
â  @jupyterlab/application-extension@^0.15.4
â  @jupyterlab/apputils-extension@^0.15.4
â  @jupyterlab/cells@^0.15.4
â  @jupyterlab/outputarea@^0.15.4
â  @jupyterlab/fileeditor@^0.15.4
â  @jupyterlab/completer@^0.15.5
â  @jupyterlab/notebook@^0.15.4
â  @jupyterlab/launcher@^0.15.4
â  @jupyterlab/docmanager@^0.15.4
â  d3-dsv@~1.0.7
â  @jupyterlab/csvviewer-extension@^0.15.4
â  @jupyterlab/docmanager-extension@^0.15.4
â  @jupyterlab/docmanager-extension@^0.15.4
â  @jupyterlab/faq-extension@^0.15.5
â  @jupyterlab/fileeditor-extension@^0.15.4
â  @jupyterlab/help-extension@^0.15.4
â  @jupyterlab/imageviewer-extension@^0.15.4
â  @jupyterlab/inspector@^0.15.4
â  @jupyterlab/json-extension@^0.15.4
â  pure-color@^1.2.0
â  @jupyterlab/mainmenu-extension@^0.4.5
â  @jupyterlab/markdownviewer-extension@^0.15.4
â  @jupyterlab/notebook-extension@^0.15.4
â  @jupyterlab/rendermime-extension@^0.9.4
â  @jupyterlab/running@^0.15.4
â  @jupyterlab/settingeditor@^0.4.4
â  @jupyterlab/settingeditor-extension@^0.10.4
â  @jupyterlab/tabmanager-extension@^0.15.4
â  xterm@~2.8.1
â  @jupyterlab/terminal-extension@^0.15.4
â  @jupyterlab/theme-dark-extension@^0.15.4
â  @jupyterlab/tooltip@^0.15.4
â  @jupyterlab/tooltip-extension@^0.15.4
â  @nteract/transform-vdom@^1.1.1
â  @jupyterlab/vega2-extension@^0.15.5
â  through2@^2.0.0
â  mime-db@~1.33.0
â  pinkie@^2.0.0
â  spdx-exceptions@^2.1.0
â  @jupyterlab/buildutils@^0.6.4
â  graceful-fs@^4.1.6
â  icss-replace-symbols@^1.1.0
â  postcss@^5.0.16
â  source-map@^0.5.3
â  handlebars@~4.0.11
â  is-buffer@^1.1.5
â  lower-case@^1.1.1
â  nth-check@~1.0.1
â  worker-farm@^1.5.2
â  p-limit@^1.1.0
â  yargs-parser@^4.2.0
â  evp_bytestokey@^1.0.0
â  evp_bytestokey@^1.0.3
â  unset-value@^1.0.0
â  kind-of@^3.0.3
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has unmet peer dependency "react@^15.6.1".
[4/4] Building fresh packages...
[1/2] â  spawn-sync
[-/2] â  waiting...
[-/2] â  waiting...
[-/2] â  waiting...
[-/2] â  waiting...
[-/2] â  waiting...
[-/2] â  waiting...
[-/2] â  waiting...
[2/2] â  canvas: gyp info spawn args   '-Goutput_dir=.' ]
[-/2] â  waiting...
[-/2] â  waiting...
warning Error running install script for optional dependency: "/home/labhub/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/canvas: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: /home/labhub/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/canvas\nOutput:\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@6.12.3 | linux | x64\ngyp info spawn /bin/python2\ngyp info spawn args [ '/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/gyp/gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'make',\ngyp info spawn args   '-I',\ngyp info spawn args   '/home/labhub/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/canvas/build/config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/home/labhub/.node-gyp/6.12.3/include/node/common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=/home/labhub/.node-gyp/6.12.3',\ngyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules.bundled/node-gyp',\ngyp info spawn args   '-Dnode_lib_file=node.lib',\ngyp info spawn args   '-Dmodule_root_dir=/home/labhub/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/canvas',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'build',\ngyp info spawn args   '-Goutput_dir=.' ]\nPackage cairo was not found in the pkg-config search path.\nPerhaps you should add the directory containing `cairo.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'cairo' found\ngyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp\ngyp ERR! configure error \ngyp ERR! stack Error: `gyp` failed with exit code: 1\ngyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/configure.js:305:16)\ngyp ERR! stack     at emitTwo (events.js:106:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:191:7)\ngyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/success Saved lockfile.
Done in 49.19s.
> node /home/labhub/.pyenv/versions/3.6.4/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.3.2
warning ../../../../../../../package.json: No license field
$ webpack --config webpack.prod.config.js
error Command failed with signal "SIGKILL".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by blink1073** [comment]
Hi @bikashdube, does it work if you use `jupyter labextension install @jupyterlab/hub-extension --dev`?

**Comment by bikashdube** [comment]
Unfortunately not. This is at the tail end and you can see with the dev option it doesn't try to go for that config.js

```
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.5.1" while you're on "1.3.2".
Done in 57.55s.
> node /home/mfdb2/.pyenv/versions/3.6.4/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build
yarn run v1.3.2
warning ../../../../../../../package.json: No license field
$ webpack
error Command failed with signal "SIGKILL".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by blink1073** [comment]
Is this a memory-constrained system?

**Comment by bikashdube** [comment]
Interesting yes just a sandbox with 1GB memory. Is that the problem in your opinion?

MemTotal:        1016108 kB

**Comment by bikashdube** [comment]
I should be allocate more memory to this for testing purposes, it is a VM on internal cloud. I will get back shortly. Why wouldn't it try to use swap ?

**Comment by blink1073** [comment]
Not sure, webpack 4 has improvements on this front but we aren't quite ready to switch

**Comment by bikashdube** [comment]
Spot on ! Bumped it to 4GB and the install went through fine (even without --dev).

```
yarn run v1.3.2
warning ../../../../../../../package.json: No license field
$ webpack --config webpack.prod.config.js
Hash: 7359515054cc17f85756
Version: webpack 2.7.0
Time: 37777ms
                                 Asset     Size  Chunks                    Chunk Names
        vendor.b9519099e3df9ec66a33.js  1.55 MB       3  [emitted]  [big]  vendor
  674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]
 fee66e712a8a08eef5805a46892932ad.woff    98 kB          [emitted]
  b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]
  912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]  [big]
             0.221d157fc3b24d73a18b.js   602 kB       0  [emitted]  [big]  vega2
             1.697f116e8467e0f2ccc6.js   458 kB       1  [emitted]  [big]
          main.b12dabf0e96c156322c6.js  1.35 MB       2  [emitted]  [big]  main
af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          [emitted]
      manifest.e1e93f1399f0d47829ae.js  1.65 kB       4  [emitted]         manifest
         0.221d157fc3b24d73a18b.js.map  2.23 MB       0  [emitted]         vega2
         1.697f116e8467e0f2ccc6.js.map  1.34 MB       1  [emitted]
      main.b12dabf0e96c156322c6.js.map  4.35 MB       2  [emitted]         main
    vendor.b9519099e3df9ec66a33.js.map  5.64 MB       3  [emitted]         vendor
  manifest.e1e93f1399f0d47829ae.js.map  8.29 kB       4  [emitted]         manifest
                            index.html  1.53 kB          [emitted]
[+HaM] ./~/@phosphor/messaging/lib/index.js 18.5 kB {3} [built]
[2Kj9] ./~/@phosphor/widgets/lib/index.js 1.34 kB {3} [built]
[8U58] ./~/codemirror/lib/codemirror.js 352 kB {3} [built]
[CUbq] ./~/@phosphor/signaling/lib/index.js 18.1 kB {3} [built]
[GiK3] ./~/react/index.js 190 bytes {3} [built]
[PJh5] ./~/moment/moment.js 123 kB {3} [built]
[Vszx] ./~/@phosphor/domutils/lib/index.js 636 bytes {3} [built]
[cYMN] ./~/@phosphor/virtualdom/lib/index.js 21 kB {3} [built]
[lMhA] ./~/@phosphor/dragdrop/lib/index.js 33.7 kB {3} [built]
[nh00] ./~/@phosphor/disposable/lib/index.js 4.24 kB {3} [built]
[qzHn] ./~/@phosphor/coreutils/lib/index.js 721 bytes {3} [built]
[ug+F] ./~/xterm/lib/xterm.js 52.7 kB {3} [built]
   [6] multi @phosphor/algorithm @phosphor/application @phosphor/commands @phosphor/coreutils @phosphor/datagrid @phosphor/disposable @phosphor/domutils @phosphor/dragdrop @phosphor/messaging @phosphor/properties @phosphor/signaling @phosphor/virtualdom @phosphor/widgets ajv ansi_up codemirror comment-json es6-promise marked moment path-posix react react-dom sanitize-html url-parse xterm 328 bytes {3} [built]
   [7] multi whatwg-fetch ./build/index.out.js 40 bytes {2} [built]
[wr2+] ./~/@phosphor/properties/lib/index.js 6.58 kB {3} [built]
    + 1462 hidden modules
Child html-webpack-plugin for "index.html":
    [3IRH] (webpack)/buildin/module.js 517 bytes {0} [built]
    [DuR2] (webpack)/buildin/global.js 509 bytes {0} [built]
    [GTAU] ./~/html-loader!./templates/partial.html 420 bytes {0} [built]
    [M4fF] ./~/lodash/lodash.js 540 kB {0} [built]
    [vxCX] ./~/html-webpack-plugin/lib/loader.js!./templates/template.html 1.41 kB {0} [built]
Done in 43.27s.
```

Good to close this with any finishing comments on your side. Hopefully this helps someone and I appreciate the support.
