### ISSUE TITLE
Unable to install and start

### ISSUE THREAD

**Issue by gta0anu** [jupyterhub/jupyterlab-hub#45]
Hi,

I followed all the steps present in the respective GitHub repositories. 

Here are the system details:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04

jupyter --version
4.4.0
jupyterhub --version
0.8.1
python --version
Python 2.7.12
python3 --version
Python 3.5.2
node --version
v8.9.4
npm --version 
5.7.1

Facing following error while starting the jupyterhub after setting the jupyterhub_config.py

[E 2018-03-06 13:41:05.373 JupyterHub user:427] Unhandled error starting ubuntu's server: [Errno 2] No such file or directory: 'jupyterhub-labhub'

Tried looking for the file in the entire system also, no luck.

jupyter labextension install @jupyterlab/hub-extension

Getting the following warning when installing via 
Command:

`jupyter labextension install @jupyterlab/hub-extension`

Error:

```
warning "@jupyterlab/json-extension > react-highlighter@0.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has unmet peer dependency "react@^15.6.1".
[4/4] Building fresh packages...
[-/2] ⠐ waiting...
[2/2] ⠐ canvas: gyp ERR!
[-/2] ⠐ waiting...
[-/2] ⠐ waiting...
warning Error running install script for optional dependency: "/usr/local/share/jupyter/lab/staging/node_modules/canvas: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: /usr/local/share/jupyter/lab/staging/node_modules/canvas\nOutput:\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.6.2\ngyp info using node@8.9.4 | linux | x64\ngyp info spawn /usr/bin/python2\ngyp info spawn args [ '/usr/lib/nodejs/node-v8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'make',\ngyp info spawn args   '-I',\ngyp info spawn args   '/usr/local/share/jupyter/lab/staging/node_modules/canvas/build/config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/usr/lib/nodejs/node-v8.9.4/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/root/.node-gyp/8.9.4/include/node/common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.9.4',\ngyp info spawn args   '-Dnode_gyp_dir=/usr/lib/nodejs/node-v8.9.4/lib/node_modules/npm/node_modules/node-gyp',\ngyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.9.4/<(target_arch)/node.lib',\ngyp info spawn args   '-Dmodule_root_dir=/usr/local/share/jupyter/lab/staging/node_modules/canvas',\ngyp info spawn args   '-Dnode_engine=v8',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'build',\ngyp info spawn args   '-Goutput_dir=.' ]\n./util/has_lib.sh: 31: ./util/has_lib.sh: pkg-config: not found\ngyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp\ngyp ERR! configure error \ngyp ERR! stack Error: `gyp` failed with exit code: 1\ngyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/nodejs/node-v8.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)\ngyp ERR! stack     at emitTwo (events.js:126:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:214:7)\ngyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_psuccess Saved lockfile.
```

**Comment by blink1073** [comment]
Hi @gta0anu, it looks like the install went fine, but the spawner command should be `jupyter-labhub` instead of `'jupyterhub-labhub`.

**Comment by gta0anu** [comment]
Hi @blink1073, that made it work. I want to ask one more thing, are we suppose to be able to logout from the JupyterLab? Because I am trying to logout and it just opens a new tav with JupyterHub login screen.

**Comment by blink1073** [comment]
I believe that is intentional, it has logged you out and is presenting you with the ability to log back in.

**Comment by gta0anu** [comment]
But the jupyterlab never logs out. Is it not supposed to logout?

**Comment by itcarroll** [comment]
I see the same behavior as @gta0anu, the notebooks in the jupyterlab tab remain fully active after "logout" ... which doesn't appear to do anything but open a new login tab.

**Comment by gta0anu** [comment]
Hi, 

Is the jupyter lab not supposed to log out?

**Comment by liffiton** [comment]
I think PR #59 fixes the logout issue.  I don't know when a new package will be uploaded to npm, though.

**Comment by blink1073** [comment]
I just pushed 0.9.1 to npm.

**Comment by gta0anu** [comment]
@blink1073 I will test out [0.9.1](https://github.com/jupyterhub/jupyterlab-hub/releases/tag/v0.9.1) and provide feedback. Thanks.

**Comment by dhirschfeld** [comment]
This can probably be closed to reduce noise in the issues list

**Comment by echyam** [comment]
I think this is related to the original issue here. The extension installed without giving me any issues, and I can run JupyterHub and JupyterLab with no problem.  But I get the following error when I try to run `sudo jupyterhub -f ./jupyterhub_config.py` with `c.Spawner.cmd = ['jupyter-labhub']` in my `jupyterhub_config.py`.
```
Unhandled error starting testuser's server: [Errno 2] No such file or directory: 'jupyter-labhub'
```
Would there any reason why JupyterHub can't find `jupyter-labhub`?

**Comment by blink1073** [comment]
Is `which jupyter-labhub` on the same root path as `which jupyterhub`?

**Comment by echyam** [comment]
`which jupyterhub` gives `/usr/local/bin/jupyterhub`
`which jupyter-labhub` gives `/home/ubuntu/anaconda3/bin/jupyter-labhub`
`which jupyter` gives `/usr/local/bin/jupyter`
That would make sense why jupyterhub can't find jupyterlab, but I installed both using conda, so I don't understand why they'd be in different directories.  Would moving `jupyter-labhub` into `/usr/local/bin/` work, or should I uninstall and re-install it?

**Comment by blink1073** [comment]
Hi @echyam, it would help to have more context about your setup.  I wasn't able to replicate in Ubuntu 18.04.  Would you mind filing a new issue and filling in the new bug report template?

**Comment by echyam** [comment]
I don't know what went wrong before (probably something to do with the configs), but I uninstalled everything and reinstalled it, and it worked.  Thanks for your help!

**Comment by blink1073** [comment]
Glad you got sorted!
