### ISSUE TITLE
[ConfigProxy] Uncaught Exception Error

### ISSUE THREAD

**Issue by bikashdube** [jupyterhub/jupyterlab-hub#52]
Select few users were able to bring up their labs on Chrome or Firefox before but lately are getting a blank page and log shows the following. There is a corresponding Linux pid also for the lab session, so the process for a user does come up but a blank page is displayed on the browser. Doesn't work in incognito modes either once bit by this bug.

09:53:32.675 - error: [ConfigProxy] Uncaught Exception Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at /usr/lib/node_modules/configurable-http-proxy/lib/configproxy.js:443:34
    at Array.map (<anonymous>)
    at ClientRequest.<anonymous> (/usr/lib/node_modules/configurable-http-proxy/lib/configproxy.js:441:46) 

```
node --version
v8.10.0

 npm --version
5.6.0

jupyterhub --version
0.8.1

```

**Comment by bikashdube** [comment]
@minrk Any input?

**Comment by bikashdube** [comment]
Well upgrading to Jupyterlab 0.32.1 actually seems to have fixed the issue. Not a lab-hub issue so closing this.
