### ISSUE TITLE
Jupyterlab-hub install failure after Jupyterlab Beta 2 upgrade

### ISSUE THREAD

**Issue by tiggerntatie** [jupyterhub/jupyterlab-hub#55]
Upon upgrading to Jupyterlab Beta 2, found I needed to reinstall the Jupyterlab-hub, but could not:

    sudo jupyter labextension install @jupyterlab/hub-extension
    > /usr/local/bin/npm pack @jupyterlab/hub-extension
    jupyterlab-hub-extension-0.8.1.tgz
    
    Errored, use --debug for full output:
    TypeError: the JSON object must be str, not 'bytes'

**Comment by dacowan** [comment]
+1

**Comment by driscolls-research** [comment]
I get the same result. Full debug output is:
`

jupyterlab-hub-extension-0.8.1.tgz
--
Fetching URL: https://registry.npmjs.org/@jupyterlab%2Fhub-extension
Traceback (most recent call last):
 
File "/opt/conda/lib/python3.5/site-packages/jupyterlab/labextensions.py", line 71, in start
ans = self.run_task()
 
File "/opt/conda/lib/python3.5/site-packages/jupyterlab/labextensions.py", line 100, in run_task
for arg in self.extra_args
 
File "/opt/conda/lib/python3.5/site-packages/jupyterlab/labextensions.py", line 100, in <listcomp>
for arg in self.extra_args
 
File "/opt/conda/lib/python3.5/site-packages/jupyterlab/commands.py", line 227, in install_extension
return handler.install_extension(extension)
 
File "/opt/conda/lib/python3.5/site-packages/jupyterlab/commands.py", line 366, in install_extension
info = self._install_extension(extension, tempdir)
 
File "/opt/conda/lib/python3.5/site-packages/jupyterlab/commands.py", line 1138, in _install_extension
version = self._latest_compatible_package_version(name)
 
File "/opt/conda/lib/python3.5/site-packages/jupyterlab/commands.py", line 1202, in _latest_compatible_package_version
metadata = _fetch_package_metadata(self.registry, name, self.logger)
 
File "/opt/conda/lib/python3.5/site-packages/jupyterlab/commands.py", line 1588, in _fetch_package_metadata
return json.load(response)
 
File "/opt/conda/lib/python3.5/json/__init__.py", line 268, in load
parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
 
File "/opt/conda/lib/python3.5/json/__init__.py", line 312, in loads
s.__class__.__name__))
 
TypeError: the JSON object must be str, not 'bytes'

`

**Comment by liffiton** [comment]
Just installed fine for me with `jupyterlab-hub-extension-0.9.0.tgz`.
```
jupyter --version     -> 4.4.0
jupyterhub --version  -> 0.8.1
jupyter-lab --version -> 0.32.0
```
